name: CD

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

  workflow_dispatch:

jobs:
  validate-prod:
    runs-on: self-hosted

    steps:
      - name: Validar PROD_TOKEN
        env:
          PROD_TOKEN: ${{ secrets.PROD_TOKEN }}
        shell: powershell
        run: |
          if ($env:PROD_TOKEN -eq $env:LOCAL_PROD_TOKEN) {
            Write-Host "PROD_TOKEN coincide con LOCAL_PROD_TOKEN"
          }
          else {
            Write-Host "PROD_TOKEN NO coincide con LOCAL_PROD_TOKEN"
            exit 1
          }
